
["Tameable Beasts Configs"]
	#Spawn Chikote
	"Chikotes spawning enabled:" = true
	#Spawn Flying Beetle
	"Flying Beetles spawning enabled:" = true
	#Spawn Roly Poly
	"Roly Polys spawning enabled:" = true
	#Spawn Grasshopper
	"Grasshoppers spawning enabled:" = true
	#Spawn Ground Beetle
	"Ground Beetles spawning enabled:" = true
	#Spawn Penguin
	"Penguins spawning enabled:" = true
	#Spawn QuetzalCoatulus
	"QuetzalCoatuluss spawning enabled:" = true
	#Spawn Racoon
	"Racoons spawning enabled:" = true
	#Spawn Crested Gecko
	"Crested Geckos spawning enabled:" = true
	#Spawn Argentavis
	"Argentavis spawning enabled:" = true
	#Spawn Grapteranodons
	"Grapteranodons spawning enabled:" = true
	#Argentavis Spawn Height
	"Argentavis minimum spawn height:" = 120
	#Quetzal Spawn Height
	"Quetzal minimum spawn height:" = 140
	#Graptera Spawn Height
	"Graptera minimum spawn height:" = 100
	#Raw Iron to Transform Ground Beetle to Metal Beetle
	"Minimum amount of Raw Iron that transforms Ground Beetle:" = 64
	#Arthropod Trim Drop Chance
	"Chance (over 100) all arthropods have of dropping Arthropod Upgrade Smithing Template upon defeat:" = 2
	#Egg Go Bad Timer
	"Seconds Eggs Take To Go Bad In The Cold:" = 120
	#Egg Hatching Timer
	"Seconds Eggs Take To Mature And Hatch:" = 1200

